name: 'hgi'
version: '1.0.0'
config-version: 2

profile: 'hgi'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  hgi:
    bronze:
      +schema: bronze
      +materialized: view
    silver:
      +schema: silver
      +materialized: view
    gold:
      +schema: gold
      +materialized: table
