-- Daily Meta ads spend, unioned across the loaded ad accounts (iS
-- Clinical, Deese PRO). Each brand's raw ADS_INSIGHTS table is
-- aggregated to one row per day, then we union and add order_month so
-- the dashboard's Month filter can target this model.
--
-- Per the project's multi-brand union convention (CLAUDE.md → Multi-brand
-- Shopify/Klaviyo union) we use one CTE trio per brand rather than
-- dbt_utils.union_relations; readable, explicit, and easy to maintain
-- when a fourth brand is added. The trio is generated by a Jinja loop
-- so the only thing that varies between brands is the source ref.

{% set brands = ['isclinical', 'deese_pro'] %}

with
{% for brand in brands %}
{{ brand }}_raw as (
    select * from {{ source('bronze_meta_' ~ brand, 'ads_insights') }}
    where date_start is not null
),
{{ brand }}_base_daily as (
    select
        date_start as spend_date,
        sum(spend) as spend,
        sum(impressions) as impressions,
        sum(clicks) as clicks
    from {{ brand }}_raw
    group by date_start
),
{{ brand }}_purchases_daily as (
    select
        r.date_start as spend_date,
        sum(case when a.value:action_type::string = 'purchase'
                 then a.value:value::float else 0 end) as purchases
    from {{ brand }}_raw r,
         lateral flatten(input => r.actions, outer => true) a
    group by r.date_start
),
{{ brand }}_purchase_value_daily as (
    select
        r.date_start as spend_date,
        sum(case when av.value:action_type::string = 'purchase'
                 then av.value:value::float else 0 end) as purchase_value
    from {{ brand }}_raw r,
         lateral flatten(input => r.action_values, outer => true) av
    group by r.date_start
),
{{ brand }} as (
    select
        b.spend_date,
        '{{ brand }}' as store_id,
        b.spend,
        b.impressions,
        b.clicks,
        coalesce(p.purchases, 0) as purchases,
        coalesce(pv.purchase_value, 0) as purchase_value
    from {{ brand }}_base_daily b
    left join {{ brand }}_purchases_daily p using (spend_date)
    left join {{ brand }}_purchase_value_daily pv using (spend_date)
){% if not loop.last %},{% endif %}
{% endfor %}

select
    spend_date,
    date_trunc('month', spend_date)::date as order_month,
    store_id,
    spend,
    impressions,
    clicks,
    purchases,
    purchase_value
from (
    {% for brand in brands %}
    select * from {{ brand }}
    {% if not loop.last %}union all{% endif %}
    {% endfor %}
)
