chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: fct_cin7_sales_order_month
            yRef:
              field: fct_cin7_sales_total_revenue
          type: bar
      xAxis:
        - axisLabel:
            formatter: "{MMMM} {yyyy}"
            hideOverlap: true
    layout:
      flipAxes: false
      xField: fct_cin7_sales_order_month
      yField:
        - fct_cin7_sales_total_revenue
  type: cartesian
contentType: chart
description: Monthly revenue across all channels from Cin7 ERP
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - fct_cin7_sales_order_month
  exploreName: fct_cin7_sales
  filters: {}
  limit: 36
  metricOverrides: {}
  metrics:
    - fct_cin7_sales_total_revenue
  sorts:
    - descending: false
      fieldId: fct_cin7_sales_order_month
  tableCalculations: []
name: Total Revenue by Month (Cin7)
slug: total-revenue-by-month-cin7
spaceSlug: shared
tableConfig:
  columnOrder:
    - fct_cin7_sales_order_month
    - fct_cin7_sales_total_revenue
tableName: fct_cin7_sales
verification: null
version: 1
